### ISSUE TITLE
cant build there message

### ISSUE THREAD

**Issue by jellewie** [jellewie/Unity-Gnorts#24]
This message should appear if the player tries to build for <1 sec> but it can't be placed down there
(Don't show directly, since we are trying to build every frame. even if we have build something in the last frame and the player mostly pressed the button longer than a frame)

See in the code:

/*TODO FIXME 
If this is hit for more than <1 sec> than show a message that we can't build there
*/

**Comment by jellewie** [comment]
Also a red outline around the building, or a red overlay on top of the building
if the building is over a spot where we can't build, would be really nice and cool

**Comment by JorisVanEijden** [comment]
Fixed by PR #77 ?

**Comment by jellewie** [comment]
Red outline is indeed done.

Just a message "Can't build on top of @e[First item that it stands on]" would be nice (This would give the user feedback that a building was tried to be placed down, and why it didn't work)
